apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zd3d4q15d-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zd3d4q15d-python 
  name: zd3d4q15d-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zd3d4q15d-python 
